### ISSUE TITLE
Fix image upload within management

### ISSUE THREAD

**Issue by brandonbk** [base-cms-websites/ac-business-media#169]
- [x] Fix issue preventing images from being uploaded
- [x] Fix issue preventing images from being removed
- [x] Update all hard-coded references for `cdn.baseplatform.io` to `p1-cms-assets-acbm.imgix.net`
- [x] Update all Ember components/controllers to use `cygnus_application.media_host` config
- [x] Update all references to Ember helpers to pass the config through to the helper to remove remaining hard-coded values

**Comment by solocommand** [comment]
Partially fixed, needs further work to remove hard-coded default of `p1-cms-assets-acbm` to work for other clients (such as ascend or allured).
